baseURL = "https://vtavernier.github.io/"
title = "The Tavern"
theme = "hugo-coder"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "en-us"

paginate = 20

[author]
name = "Vincent Tavernier"

[params]
author = "Vincent Tavernier"
info = "PhD student in Computer Graphics"
description = "Programming and research stuff"
keywords = "blog,developer,personal,research,graphics"
gravatar = "vince.tavernier@gmail.com"

favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"

footercontent = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2019

enableTwemoji = true

colorScheme = "dark"
hidecolorschemetoggle = true

customCSS = ["css/main.css"]
#customSCSS = ["scss/custom.scss"]
#customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[params.goatCounter]
code = "vtavernier"

[params.utterances]
repo = "vtavernier/vtavernier.github.io"
issueTerm = "pathname"
label = "comments"
theme = "github-dark"

# Social links
[[params.social]]
name = "E-mail"
icon = "fa fa-envelope fa-2x"
weight = 1
url = "mailto:vince.tavernier@gmail.com"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://github.com/vtavernier/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/vincent-tavernier-707b5012a/"

# Menu links
[[menu.main]]
name   = "Blog"
weight = 1
url    = "posts/"

[[menu.main]]
name   = "Projects"
weight = 2
url    = "projects/"

[[menu.main]]
name   = "Research"
weight = 3
url    = "research/"

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
unsafe = true
