name: Build pages artifacts
description: Build GitHub pages artifacts for the repository
inputs:
  base-url:
    description: Base URL
    required: false
    default: "/"
  github-token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
outputs:
  build-dir:
    description: Directory containing the artifacts
runs:
  using: docker
  image: Dockerfile
  env:
    SITE: https://vtavernier.github.io
    BASE_URL: ${{ inputs.base-url }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
