name: Build pages artifacts
description: Build GitHub pages artifacts for the repository
inputs:
  base-url:
    description: Base URL
    required: false
    default: "/"
  github-token:
    description: GitHub Token
    required: true
outputs:
  build-dir:
    description: Directory containing the artifacts
    value: ./dist
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run checks
      run: npm run ci:check
      shell: bash

    - name: Build
      run: npm run build
      env:
        SITE: https://vtavernier.github.io
        BASE_URL: ${{ inputs.base-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
