name: GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * Mon"
  workflow_dispatch:

concurrency: gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Build
        id: build
        uses: ./.github/actions/build-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ steps.build.outputs.build-dir }}
          clean-exclude: pr-preview
